# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install @angular/cli'
  displayName: 'install angular'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'src/angular/aqnkla'
    customCommand: 'install'
  displayName: 'install depedencies'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'src/angular/aqnkla'
    customCommand: 'run build-prod'
  displayName: 'build production applications'
    